import * as Yup from "yup";

export const epicContSchemas = Yup.object().shape({
  row1: Yup.object().shape({
    NBYR: Yup.string().required("NBYR is required"),
    IYR0: Yup.string().required("IYR0 is required"),
    IMO0: Yup.string().required("IMO0 is required"),
    SOLS: Yup.string().required("SOLS is required"),
    SOLO: Yup.string().required("SOLO is required"),
    ISW: Yup.string().required("ISW is required"),
    IOPS: Yup.string().required("IOPS is required"),
    IGMX: Yup.string().required("IGMX is required"),
    MASP: Yup.string().required("MASP is required"),
    LBP: Yup.string().required("LBP is required"),
    IRRS: Yup.string().required("IRRS is required"),
    NVCN: Yup.string().required("NVCN is required"),
    INFL0: Yup.string().required("INFL0 is required"),
    LBP2: Yup.string().required("LBP2 is required"),
    PHU: Yup.string().required("PHU is required"),
    SRG: Yup.string().required("SRG is required"),
    COIR: Yup.string().required("COIR is required"),
    COL: Yup.string().required("COL is required"),
    FULP: Yup.string().required("FULP is required"),
    NSTP: Yup.string().required("NSTP is required"),
  }),
  row2: Yup.object().shape({
    IGMX: Yup.string().required("IGMX is required"),
    IERT: Yup.string().required("IERT is required"),
    ICG: Yup.string().required("ICG is required"),
    LMS: Yup.string().required("LMS is required"),
    ICF: Yup.string().required("ICF is required"),
    ISW: Yup.string().required("ISW is required"),
    ICNT: Yup.string().required("ICNT is required"),
    IPST: Yup.string().required("IPST is required"),
    ICNR: Yup.string().required("ICNR is required"),
    IRU: Yup.string().required("IRU is required"),
    ILR: Yup.string().required("ILR is required"),
    IOF: Yup.string().required("IOF is required"),
    IRF: Yup.string().required("IRF is required"),
    IVC: Yup.string().required("IVC is required"),
    ISFL: Yup.string().required("ISFL is required"),
    IFLD: Yup.string().required("IFLD is required"),
    IKON: Yup.string().required("IKON is required"),
    IOG: Yup.string().required("IOG is required"),
    ISC: Yup.string().required("ISC is required"),
    ILG: Yup.string().required("ILG is required"),
    FSL: Yup.string().required("FSL is required"),
  }),
  row3: Yup.object().shape({
    CO20: Yup.string().required("CO20 is required"),
    CNO30: Yup.string().required("CNO30 is required"),
    CSLT: Yup.string().required("CSLT is required"),
    PSTX: Yup.string().required("PSTX is required"),
    YWI: Yup.string().required("YWI is required"),
    ZTK: Yup.string().required("ZTK is required"),
    FBM: Yup.string().required("FBM is required"),
    FHP: Yup.string().required("FHP is required"),
    SOLA: Yup.string().required("SOLA is required"),
    XCC: Yup.string().required("XCC is required"),
  }),
  row4: Yup.object().shape({
    GZLM: Yup.string().required("GZLM is required"),
    FFED: Yup.string().required("FFED is required"),
    DZ: Yup.string().required("DZ is required"),
    DRV: Yup.string().required("DRV is required"),
    CO2X: Yup.string().required("CO2X is required"),
    CNO3X: Yup.string().required("CNO3X is required"),
    RFNX: Yup.string().required("RFNX is required"),
    SOLQ: Yup.string().required("SOLQ is required"),
    UPS: Yup.string().required("UPS is required"),
    PEC: Yup.string().required("PEC is required"),
  }),
  row5: Yup.object().shape({
    COIR: Yup.string().required("COIR is required"),
    COL: Yup.string().required("COL is required"),
    FULP: Yup.string().required("FULP is required"),
    WAGE: Yup.string().required("WAGE is required"),
    CSTZ1: Yup.string().required("CSTZ1 is required"),
    CSTZ2: Yup.string().required("CSTZ2 is required"),
    DTG: Yup.string().required("DTG is required"),
    IDF0: Yup.string().required("IDF0 is required"),
    XKN50: Yup.string().required("XKN50 is required"),
    XKN30: Yup.string().required("XKN30 is required"),
  }),
  row6: Yup.object().shape({
    RST0: Yup.string().required("RST0 is required"),
    STF0: Yup.string().required("STF0 is required"),
    GZLM: Yup.string().required("GZLM is required"),
    FFED: Yup.string().required("FFED is required"),
    IDR0: Yup.string().required("IDR0 is required"),
    XKN1: Yup.string().required("XKN1 is required"),
  }),
  row7: Yup.object().shape({
    COIR: Yup.string().required("COIR is required"),
    COL: Yup.string().required("COL is required"),
    FULP: Yup.string().required("FULP is required"),
    WAGE: Yup.string().required("WAGE is required"),
    CSTZ1: Yup.string().required("CSTZ1 is required"),
    CSTZ2: Yup.string().required("CSTZ2 is required"),
  }),
});
